# Generated by Django 5.0.2 on 2024-03-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeesModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_Next_of_Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=50)),
                ('ID_number', models.IntegerField(max_length=9)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeForm',
        ),
    ]
